// Generated by CoffeeScript 1.3.3
(function() {
  var app, config, express, google, jade, portfolio;

  express = require('express');

  jade = require('jade');

  google = require('./reader');

  config = require('./config');

  portfolio = require('./portfolio');

  google.config(config.google);

  app = express();

  app.configure(function() {
    app.set('view engine', 'jade');
    app.set('views', "" + __dirname + "/views");
    app.set('port', process.env.PORT || 3000);
    app.use(express.bodyParser());
    app.use(express["static"](__dirname + '/public'));
    app.use(express.cookieParser());
    app.use(express.session({
      secret: "shhhhhhhhhhhhhh!"
    }));
    app.use(express.methodOverride());
    return app.use(app.router);
  });

  app.configure('development', function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure('production', function() {
    return app.use(express.errorHandler());
  });

  app.get('/', function(req, res) {
    google.listFiles(null, function(resp) {
      return portfolio.create(resp, function(arr) {
        return console.log(arr);
      });
    });
    return res.render('index', {
      title: 'Hello World!'
    });
  });

  app.get('/auth', function(req, res) {
    return google.auth(function(resp) {
      return res.redirect(resp);
    });
  });

  app.get('/oauth2callback', function(req, res) {
    return google.getToken(req.query.code, function(resp) {
      console.log(resp);
      return res.end();
    });
  });

  app.listen(app.get('port'));

  console.log("Express server listening on port " + (app.get('port')));

}).call(this);
