// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = ['image/jpeg', 'image/png', 'image/gif', 'image/bmp', 'application/x-shockwave-flash', 'audio/mpeg', 'video/mp4', 'text/html'];

}).call(this);
